# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # COMPILE PROJECT
      - name: Compile Project
        run: mvn -B compile --file pom.xml

      # UNIT-TESTS
      - name: Run UnitTests
        run: mvn -B test --file pom.xml

      # INTEGRATION-TESTS
      - name: Run IntegrationTests
        run: |
          mvn -B install --file pom.xml -Dmaven.test.skip=true
          java -jar target/*.jar &
          sleep 5
          mvn -B failsafe:integration-test --file pom.xml
          kill -9 `lsof -i:8080 -t` 

      # TEST REPORTER
      - name: Create Unit-Test Report
        uses: dorny/test-reporter@v1.6.0
        if: success() || failure()
        with:
          # Name of the check run
          name: Unit-Tests
          path: target/surefire-reports/TEST-*.xml
          reporter: java-junit

      # TEST REPORTER
      - name: Create Integration-Test Report
        uses: dorny/test-reporter@v1.6.0
        if: success() || failure()
        with:
          # Name of the check run
          name: Integration-Tests
          path: target/failsafe-reports/TEST-*.xml
          reporter: java-junit

      # UPLOAD - JACOCO REPORT
      - name: Create Code Coverage Report
        id: jacoco_reporter
        uses: PavanMudigonda/jacoco-reporter@v4.6
        with:
          coverage_results_path: target/site/jacoco/jacoco.xml
          coverage_report_name: Coverage
          coverage_report_title: JaCoCo
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_check_run: false
          minimum_coverage: 60
          fail_below_threshold: false
          publish_only_summary: false

      # UPLOAD A ARTIFACT (JACOCO REPORT)
      - name: Upload Code Coverage Report Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          # Artifact name
          name: coveragereport
          path: target/site

      # UPLOAD A ARTIFACT (DEPLOYABLE)
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          # Artifact name
          name: deployable
          # A file, directory or wildcard pattern that describes what to upload
          path: target/*.jar
          # The desired behavior if no files are found using the provided path.


      # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
